language: node_js
dist: trusty
node_js:
- '8'
- '6'
services:
- mysql
- postgresql
before_install:
- sudo pip install futoin-cid
install:
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- sudo bash test/db_config.sh
- cid tool install flyway
script:
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test

